# Import Pydantic for request/response data validation
import pydantic


# -------------------------------------------------------------------
# PDF CHUNK DATA MODEL
# -------------------------------------------------------------------

# Store document chunks and source information
class RAGChunkAndSrc(
    pydantic.BaseModel
):

    # List of text chunks extracted from PDF
    chunks: list[str]

    # Source PDF name or identifier
    source_id: str = None


# -------------------------------------------------------------------
# VECTOR INGESTION RESPONSE MODEL
# -------------------------------------------------------------------

# Response returned after vectors are inserted into Qdrant
class RAGUpsertResult(
    pydantic.BaseModel
):

    # Number of chunks/vectors successfully stored
    ingested: int


# -------------------------------------------------------------------
# VECTOR SEARCH RESPONSE MODEL
# -------------------------------------------------------------------

# Response returned after semantic similarity search
class RAGSearchResult(
    pydantic.BaseModel
):

    # Retrieved relevant text chunks
    contexts: list[str]

    # Source documents from which chunks were retrieved
    sources: list[str]


# -------------------------------------------------------------------
# FINAL RAG RESPONSE MODEL
# -------------------------------------------------------------------

# Final response generated by local LLM
class RAGQueryResult(
    pydantic.BaseModel
):

    # Generated answer from LLM
    answer: str

    # Documents used as references
    sources: list[str]

    # Number of retrieved contexts used for generation
    num_contexts: int